/** Initial quotations — 2026 seed records */
export function buildSeedQuotations() {
  return [
    {
      id: 1,
      clientName: 'Hisham Bashamakh Family',
      coverType: 'Medical',
      contactPerson: 'Zayan',
      sourceAgent: 'Zayan',
      dateReceived: '2026-01-12',
      dateSentToInsurer: null,
      insurer: 'APA',
      dateReceivedFromInsurer: null,
      status: 'Cover not taken up',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 2,
      clientName: 'Tudor Tyres & Batteries',
      coverType: 'WIBA & EL',
      contactPerson: 'Jamal',
      sourceAgent: 'Jamal',
      dateReceived: '2026-01-21',
      dateSentToInsurer: '2026-01-22',
      insurer: 'GA Insurance',
      dateReceivedFromInsurer: null,
      status: 'Cover placed',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 3,
      clientName: 'Savannah Cement',
      coverType: 'Marine',
      contactPerson: 'Nirmal',
      sourceAgent: 'Nirmal',
      dateReceived: '2026-01-26',
      dateSentToInsurer: null,
      insurer: 'GA Insurance',
      dateReceivedFromInsurer: null,
      status: 'Cover placed',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 4,
      clientName: 'Ahmed Nawd',
      coverType: 'Medical',
      contactPerson: 'Ahmed Nawd',
      sourceAgent: 'Ahmed Nawd',
      dateReceived: '2026-01-29',
      dateSentToInsurer: null,
      insurer: 'GA Insurance',
      dateReceivedFromInsurer: null,
      status: 'Client to advise',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 5,
      clientName: 'SALIM TAIB FAMILY',
      coverType: 'Medical',
      contactPerson: 'Zafir',
      sourceAgent: 'Zafir',
      dateReceived: '2026-01-29',
      dateSentToInsurer: null,
      insurer: 'Hollard',
      dateReceivedFromInsurer: null,
      status: 'Client to advise',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 6,
      clientName: 'Remington Agencies',
      coverType: 'Marine',
      contactPerson: 'Fathiya',
      sourceAgent: 'Fathiya',
      dateReceived: '2026-02-05',
      dateSentToInsurer: null,
      insurer: 'GA Insurance',
      dateReceivedFromInsurer: null,
      status: 'Cover placed',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 7,
      clientName: 'Khushi Motors',
      coverType: 'GIT',
      contactPerson: 'Yvonne',
      sourceAgent: 'Yvonne',
      dateReceived: '2026-02-12',
      dateSentToInsurer: null,
      insurer: 'GA',
      dateReceivedFromInsurer: null,
      status: 'Cover not taken up',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 8,
      clientName: 'Visual Africa Films',
      coverType: 'All Risks',
      contactPerson: 'Zafir',
      sourceAgent: 'Zafir',
      dateReceived: '2026-02-12',
      dateSentToInsurer: null,
      insurer: 'NCBA',
      dateReceivedFromInsurer: null,
      status: 'Cover placed',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 9,
      clientName: 'Wonderiss Homes Ltd',
      coverType: 'WIBA & EL',
      contactPerson: 'Beverly',
      sourceAgent: 'Beverly',
      dateReceived: '2026-02-27',
      dateSentToInsurer: null,
      insurer: 'Intra Africa/GA/NCBA',
      dateReceivedFromInsurer: null,
      status: 'Client no longer responds',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 10,
      clientName: 'Glacier Foods Ltd',
      coverType: 'Fire & Perils',
      contactPerson: 'Zafir',
      sourceAgent: 'Zafir',
      dateReceived: '2026-03-04',
      dateSentToInsurer: null,
      insurer: 'GA',
      dateReceivedFromInsurer: null,
      status: 'On hold',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 11,
      clientName: 'Coast Bus Msa Ltd',
      coverType: 'Money, FG & GPA',
      contactPerson: 'Adil',
      sourceAgent: 'Adil',
      dateReceived: '2026-03-14',
      dateSentToInsurer: null,
      insurer: 'GA Insurance',
      dateReceivedFromInsurer: null,
      status: 'Client to advise',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 12,
      clientName: 'Bellafid',
      coverType: 'WIBA',
      contactPerson: 'Fidel',
      sourceAgent: 'Fidel',
      dateReceived: '2026-03-19',
      dateSentToInsurer: null,
      insurer: 'GA/INTR/NCBA',
      dateReceivedFromInsurer: null,
      status: 'Cover placed with NCBA',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 13,
      clientName: 'Africa Polysack',
      coverType: 'Non Motor',
      contactPerson: 'Rukia',
      sourceAgent: 'Rukia',
      dateReceived: '2026-04-01',
      dateSentToInsurer: null,
      insurer: 'GA/NCBA/INTRA',
      dateReceivedFromInsurer: null,
      status: 'Client to advise',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 14,
      clientName: 'Balala & Abed Advocates',
      coverType: 'Professional Indemnity',
      contactPerson: 'Zafir',
      sourceAgent: 'Zafir',
      dateReceived: '2026-04-15',
      dateSentToInsurer: null,
      insurer: 'NCBA',
      dateReceivedFromInsurer: null,
      status: 'Cover placed',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 15,
      clientName: 'Motool Engineering',
      coverType: 'WIBA & EL',
      contactPerson: 'Zafir',
      sourceAgent: 'Zafir',
      dateReceived: '2026-04-24',
      dateSentToInsurer: null,
      insurer: 'NCBA/GA/INTRA',
      dateReceivedFromInsurer: null,
      status: 'Cover placed with NCBA',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 16,
      clientName: 'Abdi Nassir Elmi',
      coverType: 'Medical',
      contactPerson: 'Elmi',
      sourceAgent: 'Elmi',
      dateReceived: '2026-05-06',
      dateSentToInsurer: null,
      insurer: 'Now Health',
      dateReceivedFromInsurer: null,
      status: 'Client to advise',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
    {
      id: 17,
      clientName: 'Fatma Naushadali Mohamed',
      coverType: 'Medical',
      contactPerson: 'Zafir',
      sourceAgent: 'Zafir',
      dateReceived: '2026-05-11',
      dateSentToInsurer: null,
      insurer: 'Now Health',
      dateReceivedFromInsurer: null,
      status: 'Client to advise',
      notes: '',
      lastFollowUp: null,
      followUpHistory: [],
    },
  ].map((row) => ({
    ...row,
    policyNumber: '',
    premium: null,
    sumInsured: null,
    renewalDate: null,
    statusHistory: row.status
      ? [{ date: row.dateReceived, status: row.status }]
      : [],
  }))
}
